language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
script: rspec
install:
  - gem install rspec
  - gem install coveralls
before_install:
- sudo apt-get install wget -y
